id: labelManagement.issueOpened
name: GitOps.PullRequestIssueManagement
description: Handlers for when an issue is first opened
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When a PR is opened/updated, if no files are modified
          * Close the issue
          * Add a comment
        if:
          - payloadType: Pull_Request
          - isOpen
          - or:
              - isAction:
                  action: Opened
              - isAction:
                  action: Synchronize
          - filesMatchPattern:
                pattern: ^$
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},


                This pull request does not update any files. Please review your commit history and resubmit.


                Template: msftbot/validationError/pullRequest/noContent
          - closePullRequest
      - description: Add Needs-Triage to new issues
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          - addLabel:
              label: Needs-Triage

      - description: When an issue is opened, post a message to the author
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          - addReply:
              reply: |
                Hello @${issueAuthor},

                Thank you for reporting this issue, A team member will review and triage it soon. All issues are evaluated by the Arc Jumpstart team to determine next steps.
                
              label: Needs-Triage

      - description: When an issue is opened, post a message to the author
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},

                Thank you for reporting this issue, A team member will review and triage it soon. All issues are evaluated by the Arc Jumpstart team to determine next steps.
                
                By submitting this issue request, you agree that your contributions will be licensed under the project's [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).

      - description: When a PR is opened, post a message to the author
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addReply:
              reply: >-
                Hello @${issueAuthor},

                Thank you for your pull request, A team member will review it soon. All pull requests are validated by the Arc Jumpstart team and must pass all validation checks before being merged.
                
                By submitting this pull request, you agree that your contributions will be licensed under the [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE) license and you confirm that you've read and will abide by our [Code of Conduct](https://github.com/microsoft/azure_arc/blob/main/CODE_OF_CONDUCT.md).
  
      # - description: Clear labels when an issue is closed
      #   triggerOnOwnActions: false
      #   if:
      #   - payloadType: Issues
      #   - isAction:
      #       action: Closed
      #   then:
      #   - removeLabel:
      #       label: Needs-Triage
    
      # - description: Close issues that have not been triaged in 21 days
      #   resource: repository
      #   configuration:
      #       resourceManagementConfiguration:
      #       scheduledSearches:
      #         - frequencies:
      #             - daily:
      #                 time: 00:00
      #           filters:
      #             - isOpen
      #             - hasNoLabel
      #             - noActivitySince:
      #                 days: 21
      #           actions:
      #             - addReply:
      #                 reply: >-
      #                   Closing issue due to no activity in 21 days.
      #             - closeIssue
onFailure:
onSuccess: