id: moderatorTriggers
name: GitOps.PullRequestIssueManagement
description: Defines the users and permissions for the moderators
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
         then:
          # If the payload is an issue_Comment or a Pull_Request_Review_Comment
          - if:
              - or:
                  - payloadType: Issue_Comment
                  - payloadType: Pull_Request_Review_Comment
            # Remove the Needs-Triage label
            # Take different actions based on the comment pattern
            then:
              # Duplicate of #
              - if:
                  - commentContains:
                      pattern: Duplicate\s+of\s+\#?\s*\d+
                      isRegex: True
                then:
                  - addReply:
                      reply: >-
                        Hello @${issueAuthor},


                        We've identified this as a duplicate of another issue or PR that already exists. This specific instance is being closed in favor of the linked issue. Please add your 👍 to the other issue to raise its priority. Thanks for your contribution!


                        Template: msftbot/duplicate/closed
                  - closeIssue
                  - removeLabel:
                      label: Needs-Triage
                  - removeLabel:
                      label: Needs-Attention
                  - removeLabel:
                      label: Needs-Feedback-Hub
                  - removeLabel:
                      label: Needs-Author-Feedback
                  - addLabel:
                      label: Resolution-Duplicate
              
onFailure:
onSuccess: