trigger: none

parameters:
- name: ResourceGroupNamePrefix
  displayName: 'Resource Group Name prefix'
  type: string
  default: 'arcbox-itpro-tests'
- name: Location
  displayName: 'Location'
  type: string
  default: 'northeurope'
- name: AzureSubscription
  displayName: 'Azure Subscription'
  type: string
  default: 'jumpstart-ext-sub-ado-pipeline-tests-identity'
- name: githubAccount
  displayName: 'githubAccount'
  type: string
  default: 'microsoft'
- name: githubBranch
  displayName: 'githubBranch'
  type: string
  default: 'arcbox_pipeline'
- name: flavor
  displayName: 'flavor'
  type: string
  default: 'ITPro'
- name: simulateFailingTests
  displayName: 'Simulate failing tests'
  type: boolean
  default: false

variables:
#- group: 'integration-tests'
- name: ResourceGroupNamePrefix
  value: ${{parameters.ResourceGroupNamePrefix}}
- name: githubAccount
  value: ${{parameters.githubAccount}}
- name: githubBranch
  value: ${{parameters.githubBranch}}
- name: flavor
  value: ${{parameters.flavor}}
- name: Location
  value: ${{parameters.Location}}

stages:
- stage: 'ArcBox_deployment'
  jobs:
  - job: Deploy
    timeoutInMinutes: 235 # 5 minutes before the ACA self-hosted runner in order for the runner to gracefully shutdown
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: 'false'
    steps:

    - task: AzurePowerShell@5
      displayName: 'Check for failed tests'
      inputs:
        azureSubscription: ${{parameters.AzureSubscription}}
        ScriptType: 'InlineScript'
        azurePowerShellVersion: 'LatestVersion'
        Inline: |
          $failedTestsFound = $false

          # Simulate failing tests if the parameter is set
          if (${{ parameters.simulateFailingTests }}) {
              $failedTestsFound = $true
          }
          if ($failedTestsFound) {
              throw "❌ One or more Pester tests failed."
          } else {
              Write-Host "✅ All Pester tests passed." -ForegroundColor Green
          }


    - task: AzurePowerShell@5
      displayName: 'Delete resource group'
      inputs:
        azureSubscription: ${{parameters.AzureSubscription}}
        ScriptType: 'InlineScript'
        azurePowerShellVersion: 'LatestVersion'
        Inline: |
            $rgName = "$(RGname)"
            Write-Host "Deleting resource group $rgName"
            #Remove-AzResourceGroup -Name $rgName -Force
